name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: master

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "adel6-ahmed"
          outputs: "output/github-contribution-grid-snake.svg"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake contribution graph"
          branch: master
          force: true
          token: ${{ secrets.GITHUB_TOKEN }}
