name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Platane/snk@v3
        with:
          github_user_name: "adel6-ahmed"
          outputs: "output/github-contribution-grid-snake.svg|output/github-contribution-grid-snake-dark.svg"
          github_footer: false

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake*
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push
