name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # للحصول على كامل تاريخ git
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "adel6-ahmed"
          outputs: "output/github-contribution-grid-snake.svg"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Force sync and push
        run: |
          git fetch origin
          git reset --hard origin/master
          git add .
          git commit -m "Generated snake contribution graph" --allow-empty
          git push origin master --force
