name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "adel6-ahmed"
          outputs: "output/github-contribution-grid-snake.svg"

      - name: Reset and sync branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git reset --hard origin/master

      - name: Force push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake contribution graph"
          branch: master
          force: true
          token: ${{ secrets.GITHUB_TOKEN }}
