name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"  # 12:00 AM UTC يومياً
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: "adel6-ahmed"
          outputs: "snake.svg|snake-dark.svg"
          github_footer: false
          color.border: "rgba(0,0,0,0)"

      - name: Commit and push
        run: |
          # إعداد Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # إضافة الملفات
          git add snake*.svg
          
          # Commit التغييرات
          git commit -m "Auto-update snake graph [skip ci]" || echo "No changes to commit"
          
          # رفع التغييرات
          git pull --rebase origin master
          git push origin HEAD:master
